# Generated by Django 6.0.4 on 2026-05-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_youthobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awareness_opt_in', models.BooleanField(default=True)),
                ('auto_assign_counselor', models.BooleanField(default=True)),
                ('anonymize_exports', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System policies',
            },
        ),
    ]
