# Generated by Django 6.0.4 on 2026-05-29 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_systempolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=120)),
                ('actor_role', models.CharField(blank=True, max_length=40)),
                ('action', models.CharField(max_length=200)),
                ('affected_id', models.CharField(max_length=40)),
                ('domain', models.CharField(choices=[('followup', 'Follow-up'), ('digital', 'Digital')], max_length=20)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
