# Generated by Django 6.0.4 on 2026-04-29 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('missed_session', 'Séance manquée'), ('high_risk', 'Risque élevé détecté'), ('no_followup', 'Absence de suivi prolongée')], max_length=30, verbose_name="Type d'alerte")),
                ('explanation', models.TextField(verbose_name='Explication (lisible par humain)')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Résolue')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cases.case', verbose_name='Cas')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Résolue par')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField(verbose_name='Objectif')),
                ('actions', models.TextField(verbose_name='Actions planifiées')),
                ('frequency', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('biweekly', 'Bimensuel'), ('monthly', 'Mensuel')], max_length=20, verbose_name='Fréquence des séances')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_plans', to='cases.case', verbose_name='Cas')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': "Plan d'intervention",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskThresholdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_risk_threshold', models.FloatField(default=50.0, verbose_name='Seuil risque élevé (score)')),
                ('critical_risk_threshold', models.FloatField(default=75.0, verbose_name='Seuil risque critique (score)')),
                ('missed_sessions_before_alert', models.IntegerField(default=2, verbose_name='Séances manquées avant alerte')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Configuration des seuils',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Date planifiée')),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('present', 'Présent'), ('absent', 'Absent'), ('cancelled', 'Annulée')], default='scheduled', max_length=15, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cases.case', verbose_name='Cas')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
